[11:0:41:903] [客户端:初始化|信息] 已清除过期的日志文件！ 
[11:0:44:289] [客户端:初始化|信息] 窗口大小修改成功 (水平长度1920px, 垂直长度1020px) 
[11:0:44:289] [客户端:初始化|信息] 窗口位置：{X=465,Y=216} 
[11:0:44:290] [客户端:初始化|调试] 窗口PID：14416 
[11:0:44:291] [客户端:初始化|调试] 窗口句柄：2456 
[11:0:44:291] [客户端:初始化|信息] 主程序正在初始化... 
[11:0:44:295] [客户端:初始化|信息] 编辑器控件加载完毕。 
[11:0:44:296] [客户端:初始化|信息] 主程序初始化成功！ 
[11:0:44:297] [客户端:初始化|信息] 主程序初始化时间共计：0.01s 
[11:0:44:297] [客户端:初始化|信息] 初始化时间共计：6.22s 
[11:0:46:671] [客户端:主程序|信息] 已获取文件名: .py 
[11:0:48:902] [客户端:主程序|调试] ProcessStartInfo对象已创建。 
[11:0:48:902] [客户端:主程序|调试] ProcessStartInfo对象属性：FileName=.\Runner.exe, Arguments=F:\VS 2022\repos\IDE\bin\Debug\Workpace\Python\1.py 
[11:0:48:902] [客户端:主程序|调试] Process对象已创建。 
[11:0:48:998] [客户端:主程序|调试] Process对象是否已运行：True 
[11:0:49:4] [客户端:主程序|调试] Process对象标题名称： 
[11:1:18:232] [客户端:主程序|调试] ProcessStartInfo对象已创建。 
[11:1:18:232] [客户端:主程序|调试] ProcessStartInfo对象属性：FileName=.\Runner.exe, Arguments=F:\VS 2022\repos\IDE\bin\Debug\Workpace\Python\1.py 
[11:1:18:271] [客户端|致命错误] [Type System.InvalidOperationException] [HResult -2146233079] [InnerException: Null HResult Null] 已捕获异常：System.InvalidOperationException 
 异常信息：没有与此对象关联的进程。
[11:1:18:306] [客户端|致命错误] ======== 堆栈跟踪如下 ======== 
				[Outer Exception]    在 System.Diagnostics.Process.EnsureState(State state)
   在 System.Diagnostics.Process.EnsureState(State state)
   在 System.Diagnostics.Process.EnsureState(State state)
   在 System.Diagnostics.Process.get_ProcessName()
   在 IDE.Main.Run(Object sender, EventArgs e)
				[Inner Exception] (无 InnerException)
[11:1:51:280] [客户端:主程序|调试] ProcessStartInfo对象已创建。 
[11:1:51:280] [客户端:主程序|调试] ProcessStartInfo对象属性：FileName=.\Runner.exe, Arguments=F:\VS 2022\repos\IDE\bin\Debug\Workpace\Python\1.py 
[11:1:51:280] [客户端:主程序|调试] Process对象已创建。 
[11:1:51:301] [客户端:主程序|调试] Process对象是否已运行：True 
[11:1:51:305] [客户端:主程序|调试] Process对象属性：Runner 
[11:1:51:306] [客户端:主程序|调试] Process对象标题名称： 
